### ISSUE TITLE
icon组件使用onPress时候有个默认背景

### ISSUE THREAD

**Issue by chen929104** [thundersdata-frontend/td-design#155]
TouchableHighlight 上的style 

`  const roundStyle: StyleProp<ViewStyle> = {
    width: size * ratio,
    height: size * ratio,
    borderRadius: (size * ratio) / 2,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: color,
    marginBottom: 1,
  };`
backgroundColor 和 icon color 相同

**Comment by chj-damon** [comment]
已修复
