### ISSUE TITLE
使用 restyle variants 实现变体

### ISSUE THREAD

**Issue by nightwind2020** [thundersdata-frontend/td-design#301]
现在组件变体 `type?: 'primary' | 'secondary' | 'ghost';` 的实现方式没有使用 [restyle variants](https://thundersdata-frontend.github.io/td-design/restyle#variants)

请问有重构到 restyle variants 的计划吗？

**Comment by chj-damon** [comment]
请问你说的是哪个组件？目前只有Text和Tag组件有定义variant，其他组件没有

**Comment by nightwind2020** [comment]
大部分组件都不能用 variants 自定义样式，比如给按钮添加一个警告样式

**Comment by chj-damon** [comment]
是的。因为只有两个组件实现了variant，其他组件不支持。
