### ISSUE TITLE
want to have custom text in modal picker

### ISSUE THREAD

**Issue by rimsila** [thundersdata-frontend/td-design#310]
I have interest your library but I can't custom text or i18n on modal picker head left and right? 

<img width="421" alt="Screen Shot 2021-06-21 at 10 57 02 AM" src="https://user-images.githubusercontent.com/51617383/122705227-7d4fe680-d27f-11eb-8a42-2ebb2c6b6557.png">

**Comment by chj-damon** [comment]
sorry about that. I didn't expect that foreign developers would use this library.
i18N would be supported in next major version.

**Comment by rimsila** [comment]
> sorry about that. I didn't expect that foreign developers would use this library.
> i18N would be supported in next major version.

Thanks you so much for your hard work. But if you can provide like cancelText or okText with defaultProps as Chinese languages  also good for custom text.

**Comment by chj-damon** [comment]
of course, I extract `Picker` and `DatePicker` to another separate package， you can try:
```code
yarn add @td-design/react-native-picker
```

I'll release the latest version this afternoon. Thanks for your advice.

**Comment by chj-damon** [comment]
@rimsila the latest version has been released. try `yarn add @td-design/react-native-picker@latest`
