### ISSUE TITLE
Custom Theme is working but the typescript error

### ISSUE THREAD

**Issue by rimsila** [thundersdata-frontend/td-design#319]
After Custom theme td-design component is not suggest type to all component. Can we pass new theme type via T 

ex: `<ThemeProvider<NewCombineThemeType> theme={theme} > ...</ThemeProvider>`
Thanks you.

![image](https://user-images.githubusercontent.com/51617383/124211147-d7219d80-db16-11eb-9955-083e8cd6311c.png)

**Comment by chj-damon** [comment]
Thanks for your feedback, I'll try to fix it.

**Comment by chj-damon** [comment]
I think we cannot do this right now. this library depends on another project, restyle. 
the way restyle defines theme, is using `createTheme`：

```tsx
const theme = createTheme({});

export type Theme = typeof theme;
```

all the available types in this library come from `Theme`. I haven't found a nice way to let the library know the types out of the library, in which case, from our project.

**Comment by chj-damon** [comment]
I've already opened an issue: https://github.com/Shopify/restyle/issues/92 to track up this question

**Comment by rimsila** [comment]
> I think we cannot do this right now. this library depends on another project, restyle.
> the way restyle defines theme, is using `createTheme`：
> 
> ```tsx
> const theme = createTheme({});
> 
> export type Theme = typeof theme;
> ```
> 
> all the available types in this library come from `Theme`. I haven't found a nice way to let the library know the types out of the library, in which case, from our project.

> Thanks you for your trying and hardworking. however it not important because it already working except type I will ignore-ts it for now. For my idea it possible if we override theme object on app.tsx render in project that using tdDesign?.

```tsx
>tdTheme.tsx
let tdTheme ={spacing...};

export const initNewTheme = (newTheme: Record<string, any>) => {
  tdTheme = newTheme;
};

const theme = createTheme({...tdTheme});

>Project App.tsx
import { tdTheme } from '@tdDesign/....':

const overrideTheme = { ...tdTheme, spacing: { ...tdTheme.spacing, xxx: 100 } };
initNewTheme(overrideTheme);
==============
> Or I think if you can provided optional T for customize or override is possible to make TS suggestion thank you.
>td theme.tsx
export type theme<T> = typeof tdTheme & Partial<T>;
type EmptyProps<T> = BackgroundColorProps<TdTheme<Partial<T>>> 
> usage:

 <Empty<NewOverrideTheme>...</Empty>
```
