### ISSUE TITLE
建议通过 react-native-svg 的方案显示 iconfont 的图标

### ISSUE THREAD

**Issue by GreatAuk** [thundersdata-frontend/td-design#321]
https://github.com/iconfont-cli/react-native-iconfont-cli 使用很简单。
react-native-vector-icons 集成麻烦，很容易出错，而且后期新增图标也不方便。最关键的是不能热更新 !!!

**Comment by chj-damon** [comment]
非常感谢！！

**Comment by chj-damon** [comment]
改造已完成
