### ISSUE TITLE
PullRefresh changing headerDefaultText not working

### ISSUE THREAD

**Issue by rimsila** [thundersdata-frontend/td-design#323]
How Can I change refreshingText releaseText I have try but not working Can you give me the example. thanks you.

**Comment by chj-damon** [comment]
you can try to copy DefaultHeader out to your project and modify the text and then pass it to <PullRefresh HeaderComponent={YourCustomHeader} />

**Comment by chj-damon** [comment]
also, please try to run the example project first, there are some examples about these components. PullRefreshDemo may help you with this.
