### ISSUE TITLE
Bug: Picker 的值永远是初始值

### ISSUE THREAD

**Issue by GreatAuk** [thundersdata-frontend/td-design#324]
![image](https://user-images.githubusercontent.com/20253809/124850349-0d599400-dfd3-11eb-9645-34ae43234f52.png)
建议把 `value` 默认赋值为 `undefined`

**Comment by chj-damon** [comment]
相反，我有点好奇为什么不会传value

**Comment by GreatAuk** [comment]
![image](https://user-images.githubusercontent.com/20253809/124854856-96c09480-dfda-11eb-9133-0612dbb9f4ce.png)
那这个或许要改成必传属性吧。
其实如果不关注 `picker` 显示时需要默认选中哪些，只要` onChange` 的值，不值 `value` 也行的

**Comment by chj-damon** [comment]
不设为必填是为了让在表单中使用时更方便。Form会自动注入value 和 onChange属性给组件

**Comment by chj-damon** [comment]
发现了一个bug，我修复了一下，你看看是否符合你现在的预期
