### ISSUE TITLE
Bug: Picker 在 android 端的 value 类型会被转成 string

### ISSUE THREAD

**Issue by GreatAuk** [thundersdata-frontend/td-design#325]
![image](https://user-images.githubusercontent.com/20253809/125029365-1a05e700-e0bc-11eb-868c-ed64e526f751.png)
`handlePickerChange` 的输出是 ['1']  ['2'] , `number` 被转成了 `string`。 和 ios 端的行为是不一致的

大概看了下原因，想知道为什么这里要转成 `string`
![image](https://user-images.githubusercontent.com/20253809/125029516-62250980-e0bc-11eb-878f-2c0e67e30a21.png)

**Comment by chj-damon** [comment]
为了判断方便。因为这里的value的类型是string | number，所以有一种可能是这样：
[
    { label: 'text1', value: 'a' },
    { label: 'text2', value: 2 }
]

为了判断方便，就统一全转成了字符串进行比较

**Comment by GreatAuk** [comment]
"为了判断方便"？ 没懂.
```
const pickerData = [
  {
    value: 1,
    label: '11'
  },
  {
    value: 2,
    label: '22'
  }
]

function getLabel (pickerData, pickerValue) {
  pickerData.find(v => v.value === pickerValue[0]).label
}
```
这种需求应该挺常用的吧，如果用 `===` 这里就肯定报错了

**Comment by chj-damon** [comment]
这个地方确实是偷懒造成的，我改一下代码

**Comment by chj-damon** [comment]
我排查了一下，发现是RNWheelPicker这个原生组件要求的必须是字符串，所以目前只能先这样。你可以先自己做一下类型转换
