### ISSUE TITLE
inject javascript code and receive message from webview

### ISSUE THREAD

**Issue by surethink** [thundersdata-frontend/td-design#326]
thank you for the suggestion @chj-damon 

I'd like to inject such js code, but not work

`  const extraCode = `
  chart.on('click', function(param) {
    var obj = {
    type: 'event_clicked',
    data: param.data
    };
    sendData(JSON.stringify(obj));
});
`;`

the warning is 
Error evaluating injectedJavaScript: This is possibly due to an unsupported return type. Try adding true to the end of your injectedJavaScript string. Error Domain=WKErrorDomain Code=4 "A JavaScript exception occurred" UserInfo={WKJavaScriptExceptionLineNumber=3, WKJavaScriptExceptionMessage=ReferenceError: Can't find variable: chart, WKJavaScriptExceptionColumnNumber=9, WKJavaScriptExceptionSourceURL=http://localhost:8081/assets/node_modules/@td-design/react-native-echarts/lib/commonjs/tmp/tpl.html?platform=ios&hash=05a00a4c32878d73d7cd2526ff0fd832, NSLocalizedDescription=A JavaScript exception occurred}

and also , I need to receive message from webview , can this pkg support it?I don't see such feature in the demo code

  const onData = param => {
    chartRef.current.onData()
    const obj = JSON.parse(param);
    if (obj.type === "event_clicked" && obj.data.label) {
      //alert(`you tapped the chart series: ${obj.data}`);
    }
  };

**Comment by surethink** [comment]
@chj-damon

**Comment by chj-damon** [comment]
`extraCode` was injected before echarts has initialized. so you cannot find variable: chart, as the error says.

Usually, extraCode was used to do some global configuration for echarts. for example, you want to render map data, you can do this:

```js
const extraCode = `
    var shandongMapData = ${JSON.stringify(shandongMap)};
    echarts.registerMap('shandong', shandongMapData);
`;

<Echarts ref={chart} extraCode={extraCode} />
```

receive custom message from webview is not supported right now.

**Comment by surethink** [comment]
> `extraCode` was injected before echarts has initialized. so you cannot find variable: chart, as the error says.
> 
> Usually, extraCode was used to do some global configuration for echarts. for example, you want to render map data, you can do this:
> 
> ```js
> const extraCode = `
>     var shandongMapData = ${JSON.stringify(shandongMap)};
>     echarts.registerMap('shandong', shandongMapData);
> `;
> 
> <Echarts ref={chart} extraCode={extraCode} />
> ```
> 
> receive custom message from webview is not supported right now.


that's to say it can't satisfy my need now, thank you all the same ​
my scenario is a relationship network, using graph of echart , every node is an avatar, when user clicks on it , I need echart to send message from webview to react native

**Comment by chj-damon** [comment]
OK。maybe you still can fork this and add some custom code.

**Comment by surethink** [comment]
> OK。maybe you still can fork this and add some custom code.

@chj-damon  I try to fork your code and write my own, but when I test your demo code, there is still warning like this, please help to check what' wrong, thanks.  
my hermes is opened

Error evaluating injectedJavaScript: This is possibly due to an unsupported return type. Try adding true to the end of your injectedJavaScript string. Error Domain=WKErrorDomain Code=4 "A JavaScript exception occurred" UserInfo={WKJavaScriptExceptionLineNumber=2, WKJavaScriptExceptionMessage=ReferenceError: Can't find variable: bytecode, WKJavaScriptExceptionColumnNumber=11, WKJavaScriptExceptionSourceURL=undefined, NSLocalizedDescription=A JavaScript exception occurred}

**test code:**
`export default function DemoScreen({ route, navigation }) {
  const chart = useRef(null);

  useEffect(() => {
      chart.current?.setOption({
        tooltip: {
          trigger: 'axis',
          formatter: `function (params) {
            if (Array.isArray(params)) {
              return params[0].name;
            }
            return params.name;
          }`,
        },
        xAxis: {
          type: 'category',
          data: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
        },
        yAxis: {
          type: 'value',
        },
        series: [
          {
            data: [150, 230, 224, 218, 135, 147, 260],
            type: 'line',
          },
        ],
      });
  }, []);

  return (
    <View style={{ flex: 1 }}>
      <Echarts ref={chart} />
    </View>
  )
}
`
