### ISSUE TITLE
vant-react-native 求个友链

### ISSUE THREAD

**Issue by youngjuning** [thundersdata-frontend/td-design#330]

**Comment by chj-damon** [comment]
怎么加？

**Comment by youngjuning** [comment]
![image](https://user-images.githubusercontent.com/13204332/126111887-57b97afd-a0e7-4d43-8ecd-6e7c3910a212.png)

https://vant-react-native.js.org/vant-react-native/

我打算在这里加

**Comment by youngjuning** [comment]
写到推荐的 UI 组件库里

**Comment by chj-damon** [comment]
明白，我找时间改一下这个页面，增加一个模块。这两天在赶项目上线，暂时没有时间。

**Comment by chj-damon** [comment]
已加。

**Comment by youngjuning** [comment]
> 已加。

感谢，我回来也加上
