### ISSUE TITLE
DatePicker 组件在 android 闪退

### ISSUE THREAD

**Issue by GreatAuk** [thundersdata-frontend/td-design#333]
```
  <DatePicker
    title="请选择日期"
    visible={visible}
    onClose={() => setVisible(false)}
    display="Y-M-D-H-T"
    value={value}
    onChange={(value, formattedValue) => {
      setValue(value);
      setFormattedValue(formattedValue)
    }}
  />
```
在 ios 端正常使用，android 闪退，无报错

**Comment by GreatAuk** [comment]
把 `display` 属性删了就好了，看源码里面，这个属性已经不存在了

**Comment by chj-damon** [comment]
我把文档更新一下

**Comment by GreatAuk** [comment]
@chj-damon 年份这一栏在真机环境 (ios & android) 下没有显示，模拟器 (ios) 下正常。
![image](https://user-images.githubusercontent.com/20253809/126623937-b968a927-a5a3-41ec-872d-ed2ea2fed80f.png)
![image](https://user-images.githubusercontent.com/20253809/126624183-ffb5cc61-971d-4730-abbf-5fa0d6b4cd7b.png)

![image](https://user-images.githubusercontent.com/20253809/126624369-4564ee94-66c8-43bd-babb-d1c15e5af430.png)

**Comment by GreatAuk** [comment]
上面这个问题， `DatePicker` 组件的 `maxDate` 和 `minDate` 需要必填，且格式为 `YYYY-MM-DD` ，要不然年份这一栏在真机环境下就不显示

**Comment by chj-damon** [comment]
试试最新的1.5.5版本
