### ISSUE TITLE
大屏素材库开发分工

### ISSUE THREAD

**Issue by chj-damon** [thundersdata-frontend/td-design#349]
- [x] 柱线混合图  @SunshineH2 
- [x] 带背景图片的折线图  @SunshineH2 
- [x] 多折线图  @chj-damon 
 
- [x] 长方体柱状图  @chj-damon 
- [x] 圆柱图  @chj-damon 
- [x] 带阴影圆柱图  @chj-damon 
- [x] 条形图  @chj-damon 
- [x] 条形对比图  @chj-damon 
- [x] 象形图  @chj-damon 
- [x] 叠片柱状图  @chj-damon 

- [x] 环饼图  @chen929104 
- [x] #424
- [x] 带图片的饼图  @SunshineH2 
- [x] 3D饼图  @qqack 
- [x] 玫瑰图  @SunshineH2 

- [x] 数据展示1  @SunshineH2 
- [x] 数据展示2  @qqack 
- [x] 仪表盘图  @SunshineH2 
- [x] 进度条图  @SunshineH2 
- [x] 雷达图  @SunshineH2 
- [x] 散点图  @chj-damon 
- [x] 轮播图  @chj-damon 
- [x] 表格  @chj-damon 
- [x] 文字滚动  @chen929104 
- [x] 视频  @chen929104 
- [x] 词云图  @chen929104

**Comment by SunshineH2** [comment]
折线图1

**Comment by chen929104** [comment]
饼图1

**Comment by chj-damon** [comment]
第一版只考虑设计稿还原；
第二版考虑高亮、选中、Tooltip等效果；
第三版考虑自动轮播、交互效果；
第四版考虑弹窗效果；
