### ISSUE TITLE
tag组件的size太大

### ISSUE THREAD

**Issue by SunshineH2** [thundersdata-frontend/td-design#433]
设计稿上的small size的tag的总共高度才17，但是现在代码中paddingVertical是8，上下就是16，加上文本高度，导致tag高度过高，和ui稿有出入
![image](https://user-images.githubusercontent.com/31178307/143995498-80222361-184e-4ee8-823f-7b9a0e4eda6a.png)

**Comment by chj-damon** [comment]
fixed. [1bd0380](https://github.com/thundersdata-frontend/td-design/commit/1bd038023fd38d4548b14ea9ebbf0840f0352a3c)
