### ISSUE TITLE
这两个颜色不是一致的吗？为什么要加判断？

### ISSUE THREAD

**Issue by qqack** [thundersdata-frontend/td-design#436]
https://github.com/thundersdata-frontend/td-design/blob/84d59e660ca9ddb23cc3fdc92f7bfeca93b1363d/packages/react-native/src/button/index.tsx?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L39

**Comment by chj-damon** [comment]
fixed.
