### ISSUE TITLE
react-native-picker的bug

### ISSUE THREAD

**Issue by SunshineH2** [thundersdata-frontend/td-design#444]
传进去的data，是由
export enum TransformEnum {
  新牛犊 = 0,
  购入 = 1,
  出售 = 2,
  死亡 = 3,
}，转换出来包含label和value的数组，在选择新牛犊（即value为0）后，不显示label，其他三个均可正常显示

**Comment by chj-damon** [comment]
直接提供传给Picker的data出来，我复制到example里面看看

**Comment by SunshineH2** [comment]
export const TRANSFORM_TYPE = [
  { label: '新牛犊', value: 0 },
  { label: '购入', value: 1 },
  { label: '出售', value: 2 },
  { label: '死亡', value: 3 },
];

**Comment by chj-damon** [comment]
fixed
