### ISSUE TITLE
lego中的table组件中的columns设置textAlign时会报ts错误

### ISSUE THREAD

**Issue by SunshineH2** [thundersdata-frontend/td-design#472]
![image](https://user-images.githubusercontent.com/31178307/158547764-4119ad1f-84fe-412d-9191-76efea87a1ca.png)
![image](https://user-images.githubusercontent.com/31178307/158547806-1b006513-3203-4e2d-b836-89ee6f340ae2.png)

**Comment by chj-damon** [comment]
#473 fixed.
