### ISSUE TITLE
CountDown组件Props暴露resendLabel

### ISSUE THREAD

**Issue by owen800q** [thundersdata-frontend/td-design#479]
@chj-damon 

现在好像没方法直接覆盖默认的重新发送label, 考虑在CountDown props 中添加 resendLabel?

<img width="269" alt="Screenshot 2022-07-04 at 12 10 19 AM" src="https://user-images.githubusercontent.com/19252045/177047981-70bb71dd-b842-4cb9-918e-18134ff7e392.png">

**Comment by chj-damon** [comment]
谢谢反馈。你本意是想要改成什么样的？

**Comment by owen800q** [comment]
> 谢谢反馈。你本意是想要改成什么样的？

因为要支持i18N。想改成resendLabel 可以动态绑定

**Comment by chj-damon** [comment]
国际化我倒是没有考虑过。可以加一下。

**Comment by owen800q** [comment]
@chj-damon 如果这个提议ok的话，我晚点提个PR吧

**Comment by chj-damon** [comment]
非常感谢！
