### ISSUE TITLE
DatePicker can not display year value 2023

### ISSUE THREAD

**Issue by owen800q** [thundersdata-frontend/td-design#565]
@chj-damon 
The last digit being hidden. You can reproduce this issue on Iphone 13 simulator.
<img width="372" alt="Screenshot 2023-01-31 at 11 46 42 AM" src="https://user-images.githubusercontent.com/19252045/215658961-cb2b2061-cf50-4269-8926-ddbb5a3322a2.png">

**Comment by chj-damon** [comment]
感谢反馈，我看看这个问题

**Comment by 821wkli** [comment]
@chj-damon 
暫時我的解決方法可透過傳入itemStyle props 把picker 的font size 縮小。
```Javascript
      <DatePicker
        visible={visible}
        onClose={() => toggleVisible(false)}
        value={date}
        format = 'YYYY-MM-DD HH:mm'
        onChange={setDate}
        mode="date"
        cancelText="取消"
        okText="確認"
        title="選擇日期"
        style={datePickerStyles}
        itemStyle={{fontSize: px(16)}}
      />
```

Iphone 13 效果如下

<img width="347" alt="image" src="https://user-images.githubusercontent.com/42508279/215832770-46a8e3f8-d864-401b-b345-db7e1bc2c259.png">

**Comment by 821wkli** [comment]
@chj-damon 
https://github.com/react-native-picker/picker/blob/3fdddb68b3cef09626aa5d80aea5b668badf81c4/ios/RNCPicker.m#L22

測試超過20就會出現這個問題
RNCPicker font size default是21

**Comment by chj-damon** [comment]
TS应该会报错吧，暴露的类型里面没有itemStyle这个属性。有一个textSize属性可以设置字体大小，所以我需要改一下把textSize作为PickerIOS的itemStyle里面的fontSize

**Comment by 821wkli** [comment]
@chj-damon 是的，應覺只能這樣修復了

**Comment by chj-damon** [comment]
试试看新版本 4.0.2

**Comment by chj-damon** [comment]
发布了一个patch版本，你更新一下试试看

**Comment by owen800q** [comment]
Confirmed 4.0.2 already fixed this issue, thank you
