### ISSUE TITLE
無法引入@td-design/react-native-tabs， react-native-tab-view could not be found within the project 

### ISSUE THREAD

**Issue by 821wkli** [thundersdata-frontend/td-design#566]
<img width="389" alt="image" src="https://user-images.githubusercontent.com/42508279/216507181-578705d1-4856-482a-8a1e-7f7fe8c08a24.png">

Exception如下，我試了remove所有cache 重新install還是有這個問題。

error: Error: Unable to resolve module react-native-tab-view from /home/td-template/node_modules/@td-design/react-native-tabs/lib/module/Tabs.js: react-native-tab-view could not be found within the project or in these directories:
  node_modules/@td-design/react-native-tabs/node_modules
  node_modules

If you are sure the module exists, try these steps:
 1. Clear watchman watches: watchman watch-del-all
 2. Delete node_modules and run yarn install
 3. Reset Metro's cache: yarn start --reset-cache
 4. Remove the cache: rm -rf /tmp/metro-*

**Comment by 821wkli** [comment]
@chj-damon 可以把這個庫放到github嗎，想調試下看看是不是依轒有問題

**Comment by 821wkli** [comment]
已解決
```
yarn add react-native-tab-view
yarn add react-native-pager-view
cd ./ios
pod install
```

**Comment by chj-damon** [comment]
不好意思，文档没有把这两个前置依赖写清楚，我更新一下。
