### ISSUE TITLE
Carousel組件把auto設置為false時，用户手动滚动结束後會改成自動滾動

### ISSUE THREAD

**Issue by 821wkli** [thundersdata-frontend/td-design#577]
@chj-damon 
@chen929104 

如題，我是用Carousel做一個圖片預覽組件的, 就是用户以手动滚动的方式查看下一張圖, 但我把auto設置為false時，只會在組件剛渲染時生效, 當用户手动滚動查看下一張圖结束後, 就會改成自動滾動

我不確定這算不算是一個bug，還是說Carousel 組件原意是想這樣設計的?
![2023-02-19 17 03 02](https://user-images.githubusercontent.com/42508279/219939630-fae063ec-ef20-4bc7-8277-e726c3d6e211.gif)

**Comment by chj-damon** [comment]
这应该是bug，我明天看看

**Comment by 821wkli** [comment]
提了個PR, 可以明天有時間的話看看
#578
