### ISSUE TITLE
PassCode 組件 - 在驗證碼輸入完成後的回調執行getValue只能拿到前5個數字

### ISSUE THREAD

**Issue by 821wkli** [thundersdata-frontend/td-design#613]
@chj-damon 
IOS 15.6 模擬器可以復現該問題

![2023-03-30 00 57 31](https://user-images.githubusercontent.com/42508279/228613516-99777f95-4c5a-409a-9625-3383fdee93b5.gif)

加1000ms delay再調用getValue是可以拿到最新的6個數字的

![2023-03-30 00 58 39](https://user-images.githubusercontent.com/42508279/228613679-135e9f11-28b4-4092-b712-d16aebb2be26.gif)

```Javascript
 <Passcode
      ref={passCodeRef}
      clearTextOnFocus
      keyboardType="phone-pad"
      selectTextOnFocus={false}
      onChange={(value) => console.log(value)}
      onFinish={() => {1
        const inputValue = passCodeRef?.current?.getValue();
        console.log('inputValue', inputValue);
      }}
    />
```

**Comment by chj-damon** [comment]
已发布4.1.13，试试

**Comment by 821wkli** [comment]
測試ok

**Comment by chj-damon** [comment]
感谢你使用
