### ISSUE TITLE
Text 組件fontWeight 在android 沒效果

### ISSUE THREAD

**Issue by 821wkli** [thundersdata-frontend/td-design#622]
@chj-damon 
版本：4.1.16

IOS 是沒這個問題的, 我這邊測試無論Android是在模擬器還是真機都有這個問題，所有OS版本可以復現

IOS:

<img width="470" alt="image" src="https://user-images.githubusercontent.com/42508279/229999186-c6a695a2-4e9e-4e16-ae1f-dbc4ab635044.png">

Android:

<img width="1089" alt="image" src="https://user-images.githubusercontent.com/42508279/229999253-5e17a1cc-b793-4c16-b9ca-f959826a89b3.png">

**Comment by chj-damon** [comment]
https://github.com/facebook/react-native/issues/26193 看起来是RN的问题？

**Comment by chj-damon** [comment]
我试了一下，好像是组件里内内置的两个字体不支持numeric values。我把那两个字体删掉。如果需要自定义字体的话，可以自己手动通过<Text fontFamily="xxx">的方式使用

**Comment by chj-damon** [comment]
#623

**Comment by chj-damon** [comment]
4.1.17发了。你试试

现在组件库不会默认设置任何自定义字体，默认走系统自带的字体。如果你需要设置自定义字体，需要自己去配置。同时fontWeight的这个问题有可能在自定义字体上还是会有问题，这个在官方文档里有说明：https://reactnative.dev/docs/text-style-props#fontweight
