### ISSUE TITLE
tab组件的指示条和文字没有对齐

### ISSUE THREAD

**Issue by laogui** [thundersdata-frontend/td-design#682]
底部的指示条有点偏左

![Screenshot_2023-05-31-17-18-34-49_fddc075c6844b5e8eddbe65aadb01b6f.jpg](https://github.com/thundersdata-frontend/td-design/assets/3276113/74dc889c-9338-4aa1-8931-5ef70971cd27)

**Comment by chj-damon** [comment]
更新了一版，再试试
