### ISSUE TITLE
react-native 组件库 SearchBar 的问题

### ISSUE THREAD

**Issue by laogui** [thundersdata-frontend/td-design#689]
SearchBar 的新版本加了个 leftBlockStyle，宽度用了deviceWidth，导致搜索框无法和其他元素在一行。

![20230607-153150](https://github.com/thundersdata-frontend/td-design/assets/3276113/4520f958-2ccb-4bba-924a-c1fb615e56b8)
实际上右边那个图标和SearchBar是独立的，现在跑到SearchBar里面了

showCancelButton={false} 时，focus后input宽度不对
![20230607-153155](https://github.com/thundersdata-frontend/td-design/assets/3276113/ebaa8604-4682-4975-967d-5161dea220bb)

**Comment by SunshineH2** [comment]
@laogui showCancelButton={false} 时focus后input度不对的问题已经修复，稍后会进行发版。
但是你说的第一个问题，我们这个组件目前是支持传入一个children显示在左边。不知道你说的在右边显示一个其他元素，你是怎么用的，可以把代码贴出来看看

**Comment by chj-damon** [comment]
新版本已发，试试看
