### ISSUE TITLE
Picker 组件里的 WheelPicker 问题

### ISSUE THREAD

**Issue by laogui** [thundersdata-frontend/td-design#721]
https://github.com/thundersdata-frontend/td-design/blob/6c5c7fd8608bdf2ef7ef42fcaae868100bb539c0/packages/react-native-picker/src/components/WheelPicker/index.tsx#L51C9-L51C14

```
  const handleMomentumScrollEnd = (event: NativeSyntheticEvent<NativeScrollEvent>) => {
    const offsetY = Math.min(itemHeight * (data.length - 1), Math.max(event.nativeEvent.contentOffset.y, 0));
    let index = offsetY / itemHeight + 1;

    const currentItem = data[index - 1];
    if (currentItem) {
      onChange(currentItem.value);
    }
  };
```

因为前面的计算问题，得到的index不是整数，导致后面拿不到currentItem值

**Comment by chj-damon** [comment]
实际使用中倒是没有发现有问题啊，我打印出来这个index，都是正常的整数。

**Comment by chj-damon** [comment]
![image](https://github.com/thundersdata-frontend/td-design/assets/4902684/0d12909e-2323-4856-bc6f-53b61c8c09df)

**Comment by laogui** [comment]
先自己打补丁加了个Math.ceil解决了，现在有另一个问题，Modal在android上无法全屏，半透明遮罩无法覆盖statusbar。

**Comment by chj-damon** [comment]
用样式暂时无法解决这个问题。我想了一个办法，你可以控制StatusBar的hidden属性，在Modal打开的时候，把StatusBar隐藏掉，然后Modal关闭的时候把StatusBar显示出来。

**Comment by chj-damon** [comment]
发布了2.3.2版本，修复了Picker的问题。

**Comment by laogui** [comment]
今天更新了Picker组件还有两个问题：
1.  WheelPicker滑动一个条目有时候不生效，多滑几个值就没问题。还是`const _index = Math.ceil(offsetY / itemHeight) + 1
`计算有误，滑动换了一个值，但_index没变。

2.  Picker组件在ios下初始值value不生效，android没问题，每次打开都是选中第一个，用setTimeout可以解决
```
  useEffect(() => {
    setTimeout(() => {
      flatListRef.current?.scrollToIndex({
        index: selectedIndex,
        animated: false,
      })
    }, 100)
  }, [selectedIndex])
```

**Comment by chj-damon** [comment]
大佬，求PR！
