### ISSUE TITLE
请问贵司会一直更新下去吗，新项目想使用。

### ISSUE THREAD

**Issue by tankaofish** [thundersdata-frontend/td-design#781]
看了一圈rn的生态 头有点痛，贵司的框架在我看来算得上市面上最舒服的了。害怕不更新。。

**Comment by chj-damon** [comment]
会一直更新，因为我司也是 all in RN.

**Comment by tankaofish** [comment]
> 会一直更新，因为我司也是 all in RN.

如果不用脚手架的话 暂时是无法使用吗 我试了一下 貌似是不行 尝试安装了几个依赖 还是不行  脚手架这边试了 双端都ok

**Comment by chj-damon** [comment]
可能是文档上有一些没有写清楚的地方，我抽空更新一下，最近有点太忙了

**Comment by tankaofish** [comment]
> 可能是文档上有一些没有写清楚的地方，我抽空更新一下，最近有点太忙了

感谢您 期待更新

**Comment by 2460392754** [comment]
@chj-damon 我现在想通过 npm 包单独安装，还是没找到对应的文档

**Comment by chj-damon** [comment]
你直接yarn add @td-design/react-native @td-design/rn-hooks，提示缺什么库就装什么。
你也可以参考td-design/rn-template的项目配置
