### ISSUE TITLE
SearchBar 的  onChange,   onSearch 不工作

### ISSUE THREAD

**Issue by laogui** [thundersdata-frontend/td-design#782]
看代码SearchBar里面的InputItem有问题

**Comment by chj-damon** [comment]
@laogui 请问你用的是哪个版本？报错的代码可以贴一下吗？看看你是怎么写的

**Comment by chj-damon** [comment]
这两天我们刚好在项目里用到，实测下来没有发现你说的这个问题。方便的话，可以贴一下代码或者准备一个可复现的环境来方便我们进行 debug
