### ISSUE TITLE
组件开发分工

### ISSUE THREAD

**Issue by chj-damon** [thundersdata-frontend/td-design#86]
- [x] accordion 手风琴组件	@chj-damon 
- [x] action-sheet 动作面板	@chj-damon 
- [x] activity-indicator 活动指示器(整合到Toast组件)	@chj-damon 
- [x] auto-complete 自动完成输入框	@chj-damon 
- [x] avatar 头像	@chen929104 
- [x] badge 徽标		@SunshineH2 
- [x] box 盒子组件（代替react-native/View）	@chj-damon 
- [x] box-shadow 阴影组件	@chj-damon 
- [x] button 按钮	@RuanXuSong 
- [x] button-group 按钮组	@qqack 
- [x] calendar 日历	@SunshineH2 
- [x] card 卡片	@chj-damon 
- [x] swiper 轮播图
- [x] checkable 复选框/单选框	@qqack 
- [x] collapse-text 可折叠文本	@chj-damon 
- [x] date-picker 日期选择器		@chj-damon 
- [x] divider 分割线	@SunshineH2 
- [x] empty 空白组件	@tunshiyu 
- [x] flex Flex布局组件	@chj-damon 
- [x] header 头部组件	@SunshineH2 
- [x] icon 图标		@chj-damon 
- [x] image 图片		@chen929104 
- [x] image-picker 图片选择器 @RuanXuSong 
- [x] input 输入框	@chj-damon 
- [x] list-item 列表项 	@qqack 
- [x] modal 弹窗		@chj-damon 
- [x] notice-bar 通告栏 	@chj-damon 
- [x] password 密码输入框	@chen929104 
- [x] number-keyboard 数字键盘	@chen929104 
- [x] picker 选择器	@chj-damon 
- [x] progress 进度条	@chj-damon 
- [x] ratings 评分组件	@chj-damon 
- [x] search-bar 搜索框	@SunshineH2 
- [x] share 分享组件	@chj-damon 
- [x] slider 滑块	@chj-damon 
- [x] stepper 步进器	@chj-damon 
- [x] swipe-row 左滑/右滑	@chj-damon 
- [x] switch 滑动开关	@chen929104 
- [x] tabs 标签页	@chj-damon 
- [x] tag 标签	@qqack 
- [x] text 文本组件（代替react-native/Text）	@chj-damon 
- [x] toast 提示组件	@chj-damon 
- [x] white-space 上下留白	@chj-damon 
- [x] wing-blank 左右留白	@chj-damon 
- [x] float-button 悬浮按钮	@chj-damon 
- [x] data-table 表格组件	@chen929104 
- [x] flow 流程组件	@chen929104

**Comment by chj-damon** [comment]
如何认领组件开发任务？
1. 在这个issue里面comment，选择自己要开发的组件，同时备注好大概的工期。
2. 按照自己对该组件的理解，定义该组件的用途，以及罗列该组件需要的属性
3. 用伪代码举例这个组件可能的使用方式

**Comment by chj-damon** [comment]
以`WhiteSpace`组件为例：
1. 组件用途：布局控件，用于实现组件和组件之间上下留白。
2. 属性：
- `size`：枚举值。取theme.spacing下定义的尺寸。xs/s/m/l/xl/xxl。默认值为'm'。
3. 使用示例：
```jsx
<ComponentA />
<WhiteSpace />
<ComponentB />
<WhiteSpace size="m" />
<ComponentC />
```

**Comment by qqack** [comment]
`Tag`组件：
   1.预计开发用时：1天
   2.开始时间：2020/09/16
   3.组件用途：用于标记事物的属性和维度，以及进行分类。
   4.属性：

- `size`：枚举值。标签大小，可选值为large、small、default, 不写默认default。
- `disabled`：boolean。设置禁用。
- `onChange`：点击标签时触发的回调函数。
- `color`：指定标签颜色。
- `style`：自定义样式。
- `closable`: 可关闭。
- `onClose`：点关闭时的回调函数， 搭配`closable`属性使用。
- `checked`: boolean。设置标签的选中状态， 默认false。

5.使用示例：
```jsx
<Tag closable onClose={() => {}}>Movies</Tag>
<Tag size="small" disabled>disabled</Tag>
<Tag checked style={{ color: "red" }} onChange={() => {}}>checked</Tag>
````

**Comment by SunshineH2** [comment]
组件：badge
1. 预计开发用时：1天
2. 开始时间： 2020/9/15
3. 组件用途：图标右上角的红点、数字或文字，用于告知用户该区域的状态变化或待处理任务的数量
4. 属性：

- `size`：徽标的大小。枚举值。可选 `small/large`。默认值为`small`。
- `text`：展示的数字或文案，当为数字时候，大于`overflowCount`时显示为`${overflowCount}+`。类型为`string|number`。
- `overflowCount`：展示封顶的数值。类型为`number`。默认值为`99`。
- `dot`：不展示为数字，只有一个小红点。类型为`boolean`。默认值为`false`。
- `showZero`：当数值为`0`时，是否展示`Badge`。类型为`boolean`。默认值为`false`。
- `color`：自定义小圆点的颜色或数字的底色。类型为`string`。
5. 使用示例：
```
<Badge text={5}>
  <ComponentA />
</Badge>
```

**Comment by chj-damon** [comment]
![移动端组件库](https://user-images.githubusercontent.com/4902684/93161845-014fcd80-f746-11ea-89ed-0312f8d89650.png)

**Comment by chj-damon** [comment]
@SunshineH2 Badge组件还有一种形态，看上面这张图。

**Comment by chen929104** [comment]
组件：switch
预计开发用时：1天
开始时间： 2020/9/16
组件用途：一个开关，选择是否开启一个状态
checked：是否默认选中  Boolean 默认 false
disabled：是否可以修改  Boolean 默认 false
onChange：改变后的回调 
color：开关打开后的颜色
onPress：click事件触发的回调函数，当switch为disabled时，入参的值始终是默认传入的checked值。
使用示例：
 <Switch checked={true}/>

**Comment by tunshiyu** [comment]
**组件：Tabs**
1、预计开发用时：2天
2、开始时间： 2020/9/17
3、用途：便于用户在多个视图间进行切换
                allow for a consistent navigation experience between screens.
4、TabsProps:
```
interface TabsProps {
  tabs: {title: string | React.ReactNode}[];             // 字符串 或者 带有icon的tab
  initialPage?: number;                                           // 初始页
  page?: number;                                                  // 当前页
activeType?: 'normal' | 'textActive';      // 默认为normal,即下划线active样式;textActive为文字
 onChange?:(tab: Models.TabData, index: number) => void;     // tab变化时触发
 tabBarPosition?: 'top' | 'bottom';                                              // TabBar位置
  rightIcon?: ReactNode;                                                        // 右侧含有可点击的icon时
  hasGoBack?: boolean;            // 左侧为返回icon时
animated?: boolean;         // 是否开启切换动画
tabBarUnderlineStyle?:React.CSSProperties;  // tabBar下划线样式
renderTabBar?: ((props: TabBarPropsType) => React.ReactNode) | false ;       //  当需要custom替换TabBar时
}
```
5、使用:
```
  const tabs = [
      { title: 'First Tab' },
      { title: 'Second Tab' },
      { title: 'Third Tab' },
    ];

// 基础使用
    <Tabs tabs={tabs} >
           <View>
              <Text>Content of 1 Tab</Text>
          </View>
          ...
   </Tabs>

// 带有操作
 <Tabs 
tabs={tabs}   
hasGoBack
rightIcon={
        <TouchableOpacity
          onPress={() => {
            navigation.navigate('OrderSearch');
          }}
        >
          <Iconfont name="icon_search" size={px(20)} color={Color.white} />
        </TouchableOpacity>
      }
>
           <View>
              <Text>Content of 1 Tab</Text>
          </View>
          ...
   </Tabs>

// 活跃样式为文字型的
    <Tabs tabs={tabs} activeType='textActive' >
           <View>
              <Text>Content of 1 Tab</Text>
          </View>
          ...
   </Tabs>
```

**Comment by chj-damon** [comment]
@tunshiyu hasGoback, rightIcon这些属性是你自己想的吗？设计稿里面没有这些

**Comment by tunshiyu** [comment]
> @tunshiyu hasGoback, rightIcon这些属性是你自己想的吗？设计稿里面没有这些

是，之前有遇到这种场景
![image](https://user-images.githubusercontent.com/39406845/93412047-fffddc80-f8ce-11ea-9206-53111496718e.png)

**Comment by chj-damon** [comment]
@tunshiyu 按照设计规范来。或者找UI沟通

**Comment by RuanXuSong** [comment]
组件：image-picker
1.预计开发用时：2天
2.开始时间： 2020/9/17
3.组件用途：从手机选择图片或者拍照上传图片
4.属性：
- `action`：上传的地址。类型：`string`，必选。
- `data`：上传的额外参数（如：access_token）。类型：`{ [name: string]: any;}`，默认值：`{}`，可选。
- `headers`：设置上传头部。类型：{ [name: string]: any;}。默认值：`{ 'Content-Type': 'multipart/form-data',}`，可选。
- `borderStyle`：上传边框样式类型,分别为虚线框，实线框，类型：`'dashed' | 'solid'`。默认值: `'solid'`，可选。
- `icon`：中间 icon 样式类型,分别为圆框相机，新增标志，实线相机。类型：`'roundCamera' | 'plus' | 'linedCamera'`。默认值: `'roundCamera'`，可选。
- `initialImgSource`：初始化背景图,不传则没有初始背景图。类型：`ImageSourcePropType`(见 react-native-image-picker)，可选。
- `imgConfig`：
其他图片自定义配置,详细参考 react-native-image-picker的 <a href="https://github.com/react-native-- community/react-native-image-picker/blob/HEAD/docs/Reference.md">option</a> 配置，
类型：`Options`(见 react-native-image-picker)，默认值: `{}`，可选。
- `showUploadImg`：
上传图片后是否在背景图展示，如果为 `true` 上传后会自动展示上传图片(此时只能上传一张)。
类型：`boolean`，默认值: `false`，可选。
- `customRequest`:
通过覆盖默认的上传行为，可以自定义自己的上传实现，需要在 file 返回文件结果，success 返回上传是否成功 。
类型：`((file: FileProps) => { success: boolean; file: string })
    | ((file: FileProps) => Promise<{ success: boolean; file: string }>)`，可选。
- `onFailed`:上传失败事件回调，类型：`(response: Response) => void`，默认值:  暂时为`() => console.log('上传失败！')`可选。
- `onSuccess`:上传成功事件回调,返回文件路径和文件名称，类型：`(file: { fileUrl: string; fileName?: string }) => void`，默认值:  暂时为`() => console.log('上传成功！')`,可选。
- `restStyle`:其他属性将作用在外层 `ImageBackground` 背景元素上。
使用示例：
```
<ImagePicker
  action="http://object-service.dev.thundersdata.com/file/uploadToPub"
  data={{ access_token: '223bc111017d323b00fee4cf9c59a2be' }}
  borderStyle="dashed"
/>
<ImagePicker
  action="http://object-service.dev.thundersdata.com/file/uploadToPub"
  data={{ access_token: '223bc111017d323b00fee4cf9c59a2be' }}
  borderStyle="solid"
  icon="plus"
/>
<ImagePicker
  action="http://object-service.dev.thundersdata.com/file/uploadToPub"
  data={{ access_token: '223bc111017d323b00fee4cf9c59a2be' }}
  borderStyle="solid"
  icon="linedCamera"
/>
<ImagePicker
  action="http://object-service.dev.thundersdata.com/file/uploadToPub"
  data={{ access_token: '223bc111017d323b00fee4cf9c59a2be' }}
  borderStyle="solid"
  icon="linedCamera"
  showUploadImg
/>
```
![效果](https://user-images.githubusercontent.com/39564114/93559766-1aa98180-f9b3-11ea-86a4-18fd977c5861.jpg)

**Comment by tunshiyu** [comment]
组件：Empty
预计开发用时：1天
开始时间： 2020/9/18
组件用途：数据为空时的展示组件
```
type EmptyProps = BackgroundColorProps<Theme> &
  LayoutProps<Theme> & {
    /** 是否为空 */
    isEmpty: boolean;
    /** 组件样式 */
    style?: ViewStyle;
    /** 暂无数据的文字dom */
    emptyText?: string | ReactNode;
    /** 图片样式 */
    imgStyle?: ImageStyle;
    /** 组件宽高继承父级(是否填充) */
    isFill?: boolean;
  };
```
使用示例：
```
<Empty isEmpty={true} />
 <Empty isEmpty={true} backgroundColor="backgroundColor1" height={300} />
 <Box width={200} height={200} backgroundColor="warningColor1">
      <Empty isFill isEmpty={true} backgroundColor="backgroundColor1" imgStyle={{ width: 100, height: 100 }} />
 </Box>
```

**Comment by SunshineH2** [comment]
组件：Divider
1. 预计开发周期： 0.5天
2. 开始时间： 2020/9/21
3. 组件用途：区隔内容的分割线
4. 属性： 

- `type`：水平还是垂直类型。枚举值为 `horizontal` | `vertical`。默认为 `horizontal`
5. 代码示例：
```jsx
<Flex>
  <Text>我是文字A</Text>
  <Divider type="vertical" />
  <Text>我是文字B</Text>
</Flex>

<View>
  <ComponentA />
  <Divider type="horizontal" />
  <ComponentB />
</View>
```

**Comment by qqack** [comment]
`Checkable `组件：
   1.预计开发用时：2天
   2.开始时间：2020/09/27
   3.组件用途：交互组件，在一组可选项中进行多项选择或者单项选择。
   4.属性：

- `type`: 组件类型。枚举类，可选值为`checkbox|radio`, 默认`radio`
- `disabled`： 设置禁用。 boolean值。默认`false`
- `value`： 指定选中的选项。 类型: `string[] | number[]`
- `defaultValue`： 默认选项. 类型: `string[] | number[]`
- `options`：指定可选项, 类型： `string[] | number[] | Option[] `
- `onChange`：点击切换的回调函数

interface Option {
  label: string;
  value: string;
  disabled?: boolean;
}

5.使用示例：
```jsx
// 多选
<Checkable type='checkbox' defaultValue={['apple', 'peer']}, options={['apple', peer', 'banana']} />
<Checkable
  type="checkbox"
  defaultValue={['apple', 'peer']}
  options={[
    {
      label: 'apple',
      value: 'apple',
      disabled: false,
    },
    {
      label: 'peer',
      value: 'peer',
      disabled: false,
    },
    {
      label: 'banana',
      value: 'banana',
      disabled: true,
    },
  ]}
/>
// 单选
<Checkable type='radio' defaultValue={['peer']}, options={[['apple', peer', 'banana']]} />
````

**Comment by qqack** [comment]
`list-item `组件：
   1.预计开发用时：2天
   2.开始时间：2020/09/22
   3.组件用途：列表项。一般由主要信息、主要操作、次要信息、次要操作组成。主要信息和主要操作放在列表的左边，次要信息和次要操作放在列表的右边。
   4.属性：
```jsx
	interface ItemProps {
	  title: ReactNode | string; // 主标题
	  extra?: ReactNode | string; // 右面的文字
	  brief?: string | ReactNode; // 主标题下面的副标题
	  thumb?: ReactNode | null; // 图标
	  navigateTo?: string; // 跳转的stackName
	  onPress?: () => void;
	  style?: StyleProp<ViewStyle>; // 自定义style
	  isError?: boolean; // 提交表单时是否处于error状态，为true时title会标记为红色
	  arrow?: boolean; // 是否显示右边箭头
	  wrap?: boolean; // 是否折行
	  multipleLine?: boolean; // 是否显示成多行
	}
```

5.使用示例：
```jsx
<List renderHeader={'带缩略图'}>
  <Item title="主标题" brief="主标题下面的副标题" thumb="https://os.alipayobjects.com/rmsportal/mOoPurdIfmcuqtr.png" />
  <Item title="主标题" arrow=true />
  <Item
    title="extra为Image"
    extra={
      <Image
        source={{
          uri:
            'https://os.alipayobjects.com/rmsportal/mOoPurdIfmcuqtr.png',
        }}
        style={{ width: 29, height: 29 }}
      />
    }
  />
</List>
````

**Comment by RuanXuSong** [comment]
组件：`button`
1.预计开发用时：1.5 天
2.开始时间： 2020/9/23
3.组件用途：响应用户点击行为，触发相应的业务逻辑。
4.属性：
- `loading `：设置按钮加载状态。类型：`boolean`，默认值：`false`，可选。
- `type `: 按钮展示类型，默认是线框风格，ripple 水波纹风格样式为 primary，点击会出现水波纹。类型：`default | primary | ripple | link | text`，默认值：`default`，可选。
- `disabled `:按钮失效状态。类型：`boolean`，默认值：`false`，可选。
- `onClick`:  点击按钮时的回调，返回 button 的 ref 对象。类型：`(ref) => void`,可选。
- `size`:  按钮的大小，分别为 100%,50%,25% 长度 。类型: `large | middle | small`，默认值：`middle`，可选。
- `shape`:  按钮的形状，默认是小圆弧的长方形。类型：`round`|`default`，默认值：`default`，可选。
- `color`:  按钮的文字颜色，不设置则自动与主题色和按钮类型适配，类型：`string`，可选。
- `backgroundColor`: 
按钮背景色，不设置则自动与主题色和按钮类型适配，当按钮 type 为 `primary | ripple` 时，可以设置为数组，作为渐变色（从左向右），否则只取第一个颜色。
注：其他 type 不建议修改背景色。
类型:`string | [string,string]`，可选。
- `title`: 按钮文字内容，也可以用 `children` 方式传入，优先显示 `title`，类型：`ReactNode`，可选。
- `spacing` 间隔相关的属性，如 `margin`，`padding`，可选。
5.使用示例：
```
<Button type="default">默认线框按钮</Button>
<Button type="primary">primary 按钮</Button>
<Button type="ripple">水波纹按钮</Button>
<Button type="link">link 按钮</Button>
<Button type="text">text 按钮</Button>
<Button type="primary" shape="round">圆角按钮</Button>
<Button type="primary" >改变背景颜色</Button>
<Button type="primary" shape="round" backgroundColor={[theme.colors.secondaryColor,theme.colors.primaryColor]}>渐变按钮</Button>
<Button title="闭合标签写法" />
```
