### ISSUE TITLE
今天更新了Picker组件还有两个问题：

### ISSUE THREAD

**Issue by laogui** [thundersdata-frontend/td-design#862]
今天更新了Picker组件还有两个问题：
1.  WheelPicker滑动一个条目有时候不生效，多滑几个值就没问题。还是`const _index = Math.ceil(offsetY / itemHeight) + 1
`计算有误，滑动换了一个值，但_index没变。

2.  Picker组件在ios下初始值value不生效，android没问题，每次打开都是选中第一个，用setTimeout可以解决
```
  useEffect(() => {
    setTimeout(() => {
      flatListRef.current?.scrollToIndex({
        index: selectedIndex,
        animated: false,
      })
    }, 100)
  }, [selectedIndex])
```

_Originally posted by @laogui in https://github.com/thundersdata-frontend/td-design/issues/721#issuecomment-2104459796_

**Comment by chj-damon** [comment]
求PR

**Comment by chj-damon** [comment]
https://github.com/thundersdata-frontend/td-design/pull/876

这个PR应该能解决问题了

**Comment by chj-damon** [comment]
@laogui 现在遇到一个问题，就是如果一直不停地滑动，会出现跳来跳去的问题，这个问题你有什么好的办法吗？
